[[plugins]]
repo = 'Shougo/dein.vim'
[[plugins]]
repo = 'tpope/vim-endwise'
[[plugins]]
repo = 'andymass/vim-matchup'
[[plugins]]
repo = 'sheerun/vim-polyglot'
hook_add = '''
let g:polyglot_disabled = ['autoindent']
'''
