[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go', 'tmpl', 'chezmoitmpl']
hook_post_update = '''
let s:substitute_target = fnameescape('syntax/gotexttmpl.vim')
call readfile(s:substitute_target)
  \  ->writefile(s:substitute_target)
'''
