[[plugins]]
repo = 'acarapetis/vim-sh-heredoc-highlighting'
on_ft = ['sh', 'bash', 'posix']
[[plugins]]
repo = 'dense-analysis/ale'
if = false
on_ft = ['sh', 'bash', 'posix', 'markdown', 'vim']
hook_post_source = 'ALEEnable'
# autocmd VimEnter * call dein#call_hook('post_source')
