[data.env]
list = [
  { name = 'TZ', format = 'Asia/Tokyo' },
  { name = 'INPUTRC', format = '%s/readline/inputrc', expands = ['config'] },
  { name = 'PAGER', format = 'less' },
  { name = 'LESS', format = '--no-init --LONG-PROMPT --HILITE-UNREAD --RAW-CONTROL-CHARS --IGNORE-CASE --tabs=2 --shift=4' },
  { name = 'LESSHISTFILE', format = '-' },
  { name = 'NODE_REPL_HISTORY', format = '' },
  { name = 'DOCKER_CONFIG', format = '%s/docker', expands = ['config'] },
  { name = 'GNUPGHOME', format = '%s/gnupg', expands = ['data'] },
  { name = 'PASSWORD_STORE_DIR', format = '%s/pass', expands = ['data'] },
  { name = 'PYTHONSTARTUP', format = '%s/python/startup.py', expands = ['config'] },
  { name = 'GRADLE_USER_HOME', format = '%s/gradle', expands = ['data'] },
  { name = 'ANDROID_SDK_ROOT', format = '%s/.local/android-sdk', expands = ['home'] },
  { name = 'ANDROID_SDK_HOME', format = '%s/android', expands = ['data'] },
  { name = 'AWS_CONFIG_FILE', format = '%s/aws/config', expands = ['config'] },
  { name = 'AWS_SHARED_CREDENTIALS_FILE', format = '%s/aws/credentials', expands = ['config'] },
  { name = 'AZURE_CONFIG_DIR', format = '%s/azure', expands = ['config'] },
  { name = 'GOPATH', format = '%s/go', expands = ['data'] },
  { name = 'GOCACHE', format = '%s/go/build', expands = ['cache'] },
  { name = 'GOMODCACHE', format = '%s/go/pkg/mod', expands = ['cache'] },
  { name = 'HISTSIZE', format = '1000' },
  { name = 'HISTFILESIZE', format = '3000' },
  { name = 'SHELL_RC_ENV_LOADED', format = '1' },
]
